### PR TITLE
ユニークモンスター「カフモ」を追加

### LINKED ISSUE #3804: （3.0.1.5β～3.0.2.0β？）モンスター3種の追加
モンスター3種追加予定のため、それに関連することはここに書き記す

### PR DESCRIPTION
**Pull request by Slimebreath6078**
Close #3804
バランス調整は超絶大味

### CODE REVIEW

**Comment by Slimebreath6078** [comment]
以下の調整・修正をいたしました

* レア度2→3
* 純ログルスの剥奪
* 不自然な英文の修正

**Review by backwardsEric — CHANGES_REQUESTED** [review]
Google Translate (Japanese to English) gives:  "This is the fate of those who continue to seek an exit from the Amazing Digital Circus and reach their limits. Even after being sent to the basement, he still wanders around, and people can sometimes be seen getting bugs from being touched by him."  Interpolating between that and your translation, I'd suggest:

```
D:$This is the fate of those who continue to seek an exit from the Amazing Digital Circus and reach their breaking point.
D:$  He is crawling yet after being sent into the cellar.
D:$  All touched by him start abstracting.
```

In any case, to leave white space after the periods ('.'), leave one or two ~two~ spaces immediately after 'D:$' on the second two lines of the English description.

**Comment by Slimebreath6078** [comment]
I fixed exactly.
And forgot to put white space, excuse me.
Thank you.

**Review by dis- — APPROVED** [review]
英文の修正確認しました。
バランスに関して。近接攻撃力は脅威ですが、遠距離攻撃がなくカオス耐性で大幅に脅威度が落ちるため35Fとして妥当な範囲であると判断します。

**Comment by Slimebreath6078** [comment]
ご確認ありがとうございました

**Pull request merged**
