### PR TITLE
[documentation] align the contents of dungeon.txt with jdungeon.txt

### PR DESCRIPTION
**Pull request by backwardsEric**
That most notably affects the lists of feature symbols and the description of dangerous terrain. Make some minor changes to punctuation, to avoid assuming a male character, and to avoid an incomplete sentence.

### CODE REVIEW

**Review by sikabane-works — APPROVED** [review]
Thank you very much.  You have been very helpful.

**Comment by iks3** [comment]
Thank you for your jobs,
please do force push for re-activating github check.

**Review by sikabane-works — APPROVED** [review]
OK.

**Review by dis- — APPROVED** [review]
No problem at all. Thanks for your work.

**Pull request merged**
