### PR TITLE
3.0.0.0: minor English edits for src/spell-realm

### PR DESCRIPTION
**Pull request by backwardsEric**
- Change "light item" to "light" in message about the arcane spell to refuel a torch or lantern.
- Remove extraneous "do" and capitalization in the message for the onset of immunity from a craft spell.
- Fix English messages to select an item with the polish shield spell.
- Reword English message for the lapse of "An Eye for An Eye".
- Move negative from object to verb in the message about no hex spell to stop.
- Use "resume" rather than "restart" for the message about singing again.
- Drop "the" from "Judgement" when referring to the Tarot card.

### CODE REVIEW

**Review by Hourier — CHANGES_REQUESTED** [review]
"した" means 'did', so I think "歌を再開した。" is translated to "You resumed singing.".
Would you please check it?

**Review by sikabane-works — APPROVED** [review]
Thanks, I merge it.

**Comment by sikabane-works** [comment]
Oops, I don't check Houtier's comment...

**Comment by backwardsEric** [comment]
From a quick look at the other messages in spell-kind and spell-realm, most of the English messages about the result of the spell use the present tense ("Failed to swap." from spell-kind/spells-teleport.c is one that is in past tense; I don't recall seeing others).  I don't know how it's been handled in Japanese.  For English, to the extent that the message is essentially concurrent with the event, using present seems okay (an analogy would be a sporting event announcer using the present tense, "The batter swings and misses.", even though the swinging and missing is now clearly in the past).  As long as the event isn't still ongoing, the messages would work in past or present perfect tenses as well if you want to the message to clearly be from a time after the event happened.

**Review by Hourier — APPROVED** [review]
OK, I understood the usage of present/past tenses.
I approve this pull request.
Thank you for your correction!

**Pull request merged**
