### PR TITLE
GCU版の機能拡張: bigscreen / color / layout customize / cursor flicker fix

### PR DESCRIPTION
**Pull request by OwenGHB**
Implement bigscreen for curses and use it as the default behaviour. The old behaviour is still avilable using -o as a subopt for -mgcu. Also implements a new syntax for user-controlled subwindow layouts (from poschengband), documented within code comments.

### CODE REVIEW

**Comment by habu1010** [comment]
There seems to be some unnecessary whitespace and inconsistent indentation.
This project uses clang-format code formatting as a standard. (The config file is located in .clang-format in the project root.)
Is it possible to apply clang-format code formatting to main-gcu.cpp?

**Comment by OwenGHB** [comment]
I'll have a look later, but honestly I don't know anything about clang; I'm just a hacker - all my code is simply lifted from other versions or variants.

**Comment by habu1010** [comment]
If your editor does not have the ability to work with clang-format, you can install clang-format (it is probably packaged with your distribution) and run it on the command line as follows to apply code formatting.
```sh
clang-format -i src/main-gcu.cpp
```

**Comment by OwenGHB** [comment]
merged your PR, we should be good to go

**Comment by tanguband** [comment]
I tried it on a mac terminal, the following error appears when the default window size (80x24) is used.

Failed: angband needs an 80x24 map screen, not 79x23

It seems that increasing the window size works as intended.

**Comment by habu1010** [comment]
I got the same error with Ubuntu on WSL2 on Windows Terminal (80x24).
I changed line 1445 as follows, and it was displayed correctly,, but I have not been able to confirm how it affects the layout of the sub-window.
```c++
        rect_t remaining = rect(0, 0, COLS, LINES);
```

**Comment by OwenGHB** [comment]
Following discussion on angband.oook.cz, keep hengband's original color scaling where possible (thanks backwardsEric)
Following discussion on discord, stop deducting 1 from ROWS and LINES when calculating terminal dimensions

**Comment by habu1010** [comment]
I've made a few additional corrective commits to your pull request branch. Please check it and merge it.

**Comment by OwenGHB** [comment]
Got it, thanks

**Comment by habu1010** [comment]
ひとまず問題なさそうになったので、ここでマージしたいと思います。

**Review by habu1010 — APPROVED** [review]

**Pull request merged**
